"""
grid size 80x45
pixel size 1280x720
1 grid tile == 32 pixels
"""
SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1280
TILE_SIZE = 16
GRID_HEIGHT = MAP_HEIGHT = SCREEN_HEIGHT // TILE_SIZE
GRID_WIDTH =  MAP_WIDTH = SCREEN_WIDTH // TILE_SIZE
FPS = 60
ROOM_MAX_SIZE = 10
ROOM_MIN_SIZE = 6
MAX_ROOMS = 30
MAX_MONSTERS_PER_ROOM = 2